#ifndef MINSC_TEST_CODE_ANALYSIS_TEXT_SOURCE_TEXT_H_
#define MINSC_TEST_CODE_ANALYSIS_TEXT_SOURCE_TEXT_H_

#include <test/test.h>

SUITE_FUNC(state, source_text);

#endif  // MINSC_TEST_CODE_ANALYSIS_TEXT_SOURCE_TEXT_H_
