#ifndef MINSC_TEST_CODE_ANALYSIS_SYNTAX_LEXER_H_
#define MINSC_TEST_CODE_ANALYSIS_SYNTAX_LEXER_H_

#include <test/test.h>

SUITE_FUNC(state, lexer);

#endif  // MINSC_TEST_CODE_ANALYSIS_SYNTAX_LEXER_H_
