#ifndef MINSC_TEST_CODE_ANALYSIS_SYNTAX_SYNTAX_FACTS_H_
#define MINSC_TEST_CODE_ANALYSIS_SYNTAX_SYNTAX_FACTS_H_

#include <test/test.h>

SUITE_FUNC(state, syntax_facts);

#endif  // MINSC_TEST_CODE_ANALYSIS_SYNTAX_SYNTAX_FACTS_H_
