name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    strategy:
      matrix:
        include:
          - os: windows-latest
            preset: dist-win
            triplet: x64-windows
          - os: ubuntu-latest
            preset: dist
            triplet: x64-linux

    runs-on: ${{ matrix.os }}

    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: lukka/get-cmake@latest

    - uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: a1737683a6f8ec5d8673890581c2a8c55838d411

    - uses: lukka/run-cmake@v10
      with:
        configurePreset: ${{ matrix.preset }}
        buildPreset: ${{ matrix.preset }}
        testPreset: ${{ matrix.preset }}

    # don't have tests yet
#     - name: Test
#       working-directory: ${{github.workspace}}/build
#       # Execute tests defined by the CMake configuration.
#       # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
#       run: ctest -C ${{env.BUILD_TYPE}}

